apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: grafana-snippets-filter
  namespace: monitoring
spec:
  snippets:
    - context: http.server.location
      value: |
        proxy_set_header X-Forwarded-Prefix /grafana;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
